name: WebKit

on:
  workflow_run:
    workflows:
      - Lint
    types:
      - completed

jobs:
  tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: env

      - name: Setup Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Set environment variables
        run: echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/.playwright" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: microsoft/playwright-github-action@v1

      - name: Install Dependencies
        run: yarn --frozen-lockfile --no-progress --non-interactive

      - name: Test
        run: yarn test:webkit
